### ISSUE TITLE
zero_copy_bidirectional fails with error EINVAL on kernel 6.8.0

### ISSUE THREAD

**Issue by stormshield-pj50** [Hanaasagi/tokio-splice#2]
Tested by splicing two TCP sockets together: works on kernel 6.5.0, fails with error EINVAL on kernel 6.8.0.

strace output:
``
[pid 27024] splice(15, NULL, 19, NULL, 18446744073709551615, SPLICE_F_NONBLOCK) = -1 EINVAL (Invalid argument)
``

Seems to be related to usize::MAX length passed to syscall splice, instead use a length of 65536 for example and it works on kernel 6.8.0.

I can provide a pull request if you want.

**Comment by Hanaasagi** [comment]
Thank you for discovering and fixing this issue.
